name: Extract ZIP
on: [push]
jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Unzip file
        run: unzip arquivo.zip -d extraído/
